// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
import { existsSync } from "node:fs";
import { config as dotenvConfig } from "dotenv";

// Load environment file for Prisma CLI.
// Prisma by default loads `.env`; in a Next.js project secrets are often in `.env.local`.
const prismaEnvPath = existsSync(".env")
  ? ".env"
  : existsSync(".env.local")
    ? ".env.local"
    : undefined;

if (prismaEnvPath) {
  dotenvConfig({ path: prismaEnvPath });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
